### PR TITLE
Fix/query param support

### PR DESCRIPTION
**Pull request by F-Shahali**
#### Reference Issues/PRs
#26 
#### What does this implement/fix? Explain your changes.
Resolve the indirect mode issue by handling `path` query param to detect the target path and redirect to the relevant route (for example if we have `path=share` as a query param, it would be redirected to `/share` route).
#### Any other comments?
After applying these changes, any other routes would be reachable by a direct link. Like this: `https://mybutton.click/?path=get`

### CODE REVIEW

**Review by AHReccese — CHANGES_REQUESTED** [review]
image
Thank you for your effort, But I don't think redirecting entirely solves the problem, because after redirection, browser will still send a request and GitHub proxy will treat the redirected link as a request to find a file in `share` directory and it will fail again.

**Review by AHReccese — CHANGES_REQUESTED** [review]
I've sent you a video in Telegram, explaining the case and how a correct addressing would be look like, I hope you can go ahead and fix it.

**Comment by F-Shahali** [comment]
I removed the navigation structure for all paths and now routing is handled by query param support.
It's ready for your re-reviewing.
@AHReccese

**Review by AHReccese — APPROVED** [review]
LGTM
Thanks for your efforts

**Pull request merged**
