### PR TITLE
New Services & 404 Page

### PR DESCRIPTION
**Pull request by F-Shahali**
#### Reference Issues/PRs
#35 #36  #46
#### What does this implement/fix? Explain your changes.
- Add `Hacker News` & `Yahoo Mail` services
- Add a custom 404 page (will be enabled on the main domain)
- Minor edit on the primary color of the project to make it a bit lighter

### CODE REVIEW

**Comment by AHReccese** [comment]
image

Thank you Fatemeh @F-Shahali for your effort, I liked the 404 page a lot! nice one!
I tested `Yahoo` and `Hacker News`, they both worked fine, but `WhatsApp` didn't worked well, the link for `href` is `undefined`.

**Review by AHReccese — CHANGES_REQUESTED** [review]
Take a look at my comment.

**Comment by AHReccese** [comment]
@sepandhaghighi let us know your review too.
Thanks.

**Comment by F-Shahali** [comment]
> image
> Thank you Fatemeh @F-Shahali for your effort, I liked the 404 page a lot! nice one! I tested `Yahoo` and `Hacker News`, they both worked fine, but `WhatsApp` didn't worked well, the link for `href` is `undefined`.
> 
> It happened in the `direct` mode, and in the `indirect` mode after clicking on the service icon, it ends up with infinite loading.
> 
> I'm in desktop and I do have WhatsApp installed.

So happy you liked it!
Thanks for your report, I'll fix it.

**Review by sepandhaghighi — CHANGES_REQUESTED** [review]
@F-Shahali Thanks for your efforts 💯 Well done.
Please update `Supported services` table in `README.md`.

@AHReccese While you are correct about `WhatsApp` bug, I believe it is beyond the scope of this PR. We should address it in a separate one.

**Review by sepandhaghighi — APPROVED** [review]
LGTM 🚀

**Review by AHReccese — APPROVED** [review]

**Pull request merged**
